import {useEffect,useMemo,useState} from 'react';
import {PawPrint,MapPin,ChevronDown,MousePointer2,Info} from 'lucide-react';
import Controls from './components/Controls.jsx';
import Inspector from './components/Inspector.jsx';
import MapCanvas from './components/MapCanvas.jsx';
import Timeline from './components/Timeline.jsx';
import Methodology from './components/Methodology.jsx';
import {createDemo,parseOSM,fetchRealData,parseCadastre} from './geography.js';
import {DEFAULTS,simulate,statistics,tripState} from './simulation.js';
export default function App(){
 const [graph,setGraph]=useState(createDemo),[settings,setSettings]=useState(DEFAULTS),[time,setTime]=useState(18*60+30),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(60),[layers,setLayers]=useState({flows:true,stops:true,housing:true,parcels:true}),[parcels,setParcels]=useState([]),[method,setMethod]=useState(false),[placing,setPlacing]=useState(false),[radius,setRadius]=useState(30),[point,setPoint]=useState(()=>({p:[-47,36],name:'Point exploratoire'})),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const sim=useMemo(()=>simulate(graph,settings),[graph,settings]);const stats=useMemo(()=>statistics(sim,point?.p||[0,0],radius),[sim,point,radius]);const active=useMemo(()=>sim.trips.reduce((n,t)=>n+(tripState(t,time)?t.weight:0),0),[sim,time]);
 useEffect(()=>{if(!playing)return;let previous=performance.now();const timer=setInterval(()=>{const now=performance.now(),delta=(now-previous)/1000;previous=now;setTime(t=>(t+delta*speed/60)%1440);},100);return()=>clearInterval(timer);},[playing,speed]);
 useEffect(()=>{const controller=new AbortController();fetch('/data/chatillon.json',{signal:controller.signal}).then(r=>r.ok?r.json():null).then(data=>{if(data?.osm&&data?.commune){const g=parseOSM(data.osm,data.commune);setGraph(g);if(g.population)setSettings(s=>({...s,population:g.population}));setPoint({p:g.nodes[Math.floor(g.nodes.length/2)].p,name:g.nodes[Math.floor(g.nodes.length/2)].name});}}).catch(()=>{});return()=>controller.abort();},[]);
 useEffect(()=>{const controller=new AbortController();fetch('/data/parcels.json',{signal:controller.signal}).then(r=>r.ok?r.json():null).then(data=>{if(data)setParcels(parseCadastre(data));}).catch(()=>{});return()=>controller.abort();},[]);
 useEffect(()=>{if(!method)return;const escape=e=>{if(e.key==='Escape')setMethod(false);};document.addEventListener('keydown',escape);const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',escape);document.body.style.overflow=before;};},[method]);
 const loadReal=async()=>{setLoading(true);setError('');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);try{const data=await fetchRealData(controller.signal),g=parseOSM(data.osm,data.commune);setGraph(g);if(g.population)setSettings(s=>({...s,population:g.population}));setPoint({p:g.nodes[Math.floor(g.nodes.length/2)].p,name:g.nodes[Math.floor(g.nodes.length/2)].name});}catch{setError('Les sources ne sont pas accessibles depuis ce navigateur (réseau ou CORS). Sur votre Mac, exécutez npm run data:fetch puis relancez le site. Le mode démonstration reste disponible.');}finally{clearTimeout(timer);setLoading(false);}};
 const exportData=()=>{const rows=['heure;promenades_estimees;rayon_m;graine;mode',...stats.hours.map((v,h)=>`${h};${v};${radius};${settings.seed};${graph.mode}`)];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.join('\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='kifaitpipi-passages.csv';a.click();URL.revokeObjectURL(url);};
 return <div className="app-shell"><header className="header"><a className="brand" href="#" aria-label="Kifaitpipi, accueil"><PawPrint size={29} fill="currentColor" strokeWidth={1.5}/><span>kifaitpipi</span></a><nav aria-label="Navigation principale"><button className={!method?'active':''} onClick={()=>setMethod(false)}>Simulation</button><button className={method?'active':''} onClick={()=>setMethod(true)}>Méthodologie</button></nav><div className="location"><MapPin size={17}/><span>Châtillon, Hauts-de-Seine</span><ChevronDown size={15}/></div></header><div className="workspace"><Controls settings={settings} setSettings={setSettings} layers={layers} setLayers={setLayers} graph={graph} parcels={parcels} showMethod={()=>setMethod(true)}/><main className="main"><div className="map-area"><MapCanvas parcels={parcels} graph={graph} sim={sim} time={time} layers={layers} point={point} radius={radius} placing={placing} onPoint={p=>{setPoint(p);setPlacing(false);}}/><div className="map-title"><h2>Châtillon</h2><p>Une ville, des milliers de parcours.</p><button className="data-status" onClick={()=>setMethod(true)}><span className={graph.mode==='real'?'status-dot real':'status-dot'}/>{graph.mode==='real'?(layers.parcels&&parcels.length?'Cadastre réel · flux simulés':'Géographie réelle · hypothèses simulées'):'Démonstration · fond schématique'}<Info size={12}/></button></div><button className={`place-button ${placing?'selected':''}`} onClick={()=>setPlacing(v=>!v)}><MapPin size={16}/>{placing?'Cliquez sur la carte':'Placer un point'}</button>{point?<Inspector point={point} stats={stats} radius={radius} setRadius={setRadius} time={time} onClose={()=>setPoint(null)}/>:<div className="empty-inspector"><MousePointer2 size={22}/><strong>Où passent les promenades ?</strong><p>Cliquez sur la carte pour analyser un point.</p></div>}<div className="map-bottom"><div className="activity"><span className="live-dot"/>{Math.round(active).toLocaleString('fr-FR')} chiens simulés en balade</div><div className="legend"><span><i className="line-key"/>Promenade</span><span><i className="stop-key"/>Arrêt simulé</span><span><i className="housing-key"/>Résidentiel</span>{parcels.length&&layers.parcels?<span><i className="parcel-key"/>Cadastre</span>:null}</div></div><div className="attribution">{graph.source}{parcels.length&&layers.parcels?' · DGFiP / IGN':null}</div></div><Timeline time={time} setTime={setTime} playing={playing} setPlaying={setPlaying} speed={speed} setSpeed={setSpeed} day={settings.day} setDay={day=>setSettings(s=>({...s,day}))}/><div className="mobile-note"><Info size={13}/> Simulation exploratoire · données non observées <button onClick={()=>setMethod(true)}>Sources</button></div></main></div>{method?<Methodology onClose={()=>setMethod(false)} settings={settings} setSettings={setSettings} graph={graph} parcels={parcels} loadReal={loadReal} loading={loading} error={error} sim={sim} exportData={exportData}/>:null}</div>;
}
